// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import type { Locales, Translations } from './i18n-types.js'
import { initFormatters } from './formatters.js'
import { loadedFormatters, loadedLocales, locales } from './i18n-util.js'

const localeTranslationLoaders = {
  de: () => import('./de/index.js'),
  en: () => import('./en/index.js'),
  es: () => import('./es/index.js'),
  fr: () => import('./fr/index.js'),
  hi: () => import('./hi/index.js'),
  it: () => import('./it/index.js'),
  iw: () => import('./iw/index.js'),
  ja: () => import('./ja/index.js'),
  ru: () => import('./ru/index.js'),
}

function updateDictionary(locale: Locales, dictionary: Partial<Translations>): Translations {
  return loadedLocales[locale] = { ...loadedLocales[locale], ...dictionary }
}

export async function importLocaleAsync(locale: Locales): Promise<Translations> {
  return (await localeTranslationLoaders[locale]()).default as unknown as Translations
}

export async function loadLocaleAsync(locale: Locales): Promise<void> {
  updateDictionary(locale, await importLocaleAsync(locale))
  loadFormatters(locale)
}

export const loadAllLocalesAsync = (): Promise<void[]> => Promise.all(locales.map(loadLocaleAsync))

export function loadFormatters(locale: Locales): void {
  return void (loadedFormatters[locale] = initFormatters(locale))
}
